### ISSUE TITLE
ERROR Cannot start nuxt: kit.writeTypes is not a function

### ISSUE THREAD

**Issue by imcm7** [Hebilicious/authjs-nuxt#90] opened 2023-09-08 05:44 UTC
### Environment

Nuxt project info:                                                                                                                                        8:15:37 AM

------------------------------
- Operating System: Linux
- Node Version:     v20.5.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.0
- Nitro Version:    2.6.3-28235083.5639f5b
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      alias, app, colorMode, css, dayjs, devtools, experimental, i18n, image, modules, nitro, pwa, runtimeConfig, security, ssr, tailwindcss, viewport, vueEmail
- Runtime Modules:  @hebilicious/authjs-nuxt@0.2.0-beta.8, @nuxt/image@1.0.0-rc.1, @nuxtjs/color-mode@3.3.0, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @vee-validate/nuxt@4.11.3, @vueuse/nuxt@10.4.1, dayjs-nuxt@1.1.2, nuxt-security@0.14.4, nuxt-viewport@2.0.6, vue3-carousel-nuxt@1.1.0, vue-email/nuxt
- Build Modules:    -
------------------------------

### Reproduction

New instaled nuxt with modules

@hebilicious/authjs-nuxt@0.2.0-beta.8, @nuxt/image@1.0.0-rc.1, @nuxtjs/color-mode@3.3.0, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @vee-validate/nuxt@4.11.3, @vueuse/nuxt@10.4.1, dayjs-nuxt@1.1.2, nuxt-security@0.14.4, nuxt-viewport@2.0.6, vue3-carousel-nuxt@1.1.0, vue-email/nuxt

### Describe the bug

-Nuxt 3.7.1 with Nitro 2.6.3-28235083.5639f5b                                                                                                              8:14:07 AM
                                                                                                                                                          8:14:09 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Adding @auth/nuxt module... { verifyClientOnEveryRequest: true,                                                                             @auth/nuxt 8:14:12 AM
  guestRedirectTo: '/',
  authenticatedRedirectTo: '/',
  baseUrl: '' }
✔ Added @auth/nuxt module successfully.                                                                                                       @auth/nuxt 8:14:12 AM
ℹ Vue I18n configuration file does not exist at i18n.config. Skipping...                                                                    @nuxtjs/i18n 8:14:13 AM
ℹ Using default Tailwind CSS file                                                                                                       nuxt:tailwindcss 8:14:13 AM
ℹ Using yup with vee-validate                                                                                                                            8:14:14 AM
✔ Nuxt DevTools is enabled v0.8.3 (experimental)                                                                                                         8:14:16 AM
ℹ Tailwind Viewer: http://127.0.0.1:33087/_tailwind/                                                                                    nuxt:tailwindcss 8:14:17 AM

 ERROR  Cannot start nuxt:  kit.writeTypes is not a function                                                                                              8:14:17 AM

  at NuxtDevServer._load (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/chunks/dev.mjs:230:11)
  at async NuxtDevServer.load (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/chunks/dev.mjs:161:7)
  at async NuxtDevServer.init (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/chunks/dev.mjs:156:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/chunks/dev-child.mjs:91:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/shared/nuxi.913ed971.mjs:1645:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/shared/nuxi.913ed971.mjs:1639:7)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/shared/nuxi.913ed971.mjs:1757:7)

**Comment by FamilyMan** [comment] 2023-09-08 08:36
I also get this. My dependencies are:

  "devDependencies": {
    "@hebilicious/authjs-nuxt": "^0.3.0-beta.2",
    "nuxt": "^3.7.1"
  }

Just having this and running "npm run dev" gives me the same error as above.

**Comment by Hebilicious** [comment] 2023-09-08 11:45
> I also get this. My dependencies are:
> 
> "devDependencies": { "@hebilicious/authjs-nuxt": "^0.3.0-beta.2", "nuxt": "^3.7.1" }
> 
> Just having this and running "npm run dev" gives me the same error as above.

Can you downgrade Nuxt to 3.7.0 and let me know if that fixes the issue for you ?

**Comment by FamilyMan** [comment] 2023-09-08 12:12
Downgrading to 3.7.0 doesn't fix it, but downgrading to 3.6.5 does

**Comment by Hebilicious** [comment] 2023-09-08 13:06
> Downgrading to 3.7.0 doesn't fix it, but downgrading to 3.6.5 does

Thanks for the heads-up, we're investigating.

**Comment by ray2ding** [comment] 2023-09-08 15:09
> Downgrading to 3.7.0 doesn't fix it, but downgrading to 3.6.5 does

Thank you, downgrade to 3.6.5 works for me too

**Comment by Hebilicious** [comment] 2023-09-08 17:55
Btw if you guys have a reproduction that would be great. I tried to reproduce with nuxt 3.7.1 but no luck, everything works on my end : https://github.com/Hebilicious/nuxt-cli-module-issue

**Comment by FamilyMan** [comment] 2023-09-08 18:15
Interesting. What version of Node are you using? I'm currently on 18.17.1
I will try 20.6.1 and see if that makes any difference.

**Comment by Hebilicious** [comment] 2023-09-08 19:36
> Interesting. What version of Node are you using? I'm currently on 18.17.1 I will try 20.6.1 and see if that makes any difference.

20.5.0, but I'm using bun, not node.

**Comment by FamilyMan** [comment] 2023-09-08 21:38
I can confirm that upgrading Node to 20.6.1, this fixes the issue. I can install this package and use Nuxt 3.7.1

**Comment by Hebilicious** [comment] 2023-09-08 22:00
> I can confirm that upgrading Node to 20.6.1, this fixes the issue. I can install this package and use Nuxt 3.7.1

That seems very odd ... I'm gonna close this so we can track in https://github.com/nuxt/cli/issues/157

**Comment by Hebilicious** [comment] 2023-09-09 15:03
fixed in https://github.com/nuxt/cli/pull/158

**Closed by Hebilicious** 2023-09-09 15:03 UTC
Labels: bug, upstream, workaround available, nuxt
