### ISSUE TITLE
TypeError: crypto.getRandomValues is not a function       

### ISSUE THREAD

**Issue by imcm7** [Hebilicious/authjs-nuxt#17] opened 2023-07-04 12:33 UTC
### Environment

[auth][error][SignInError]: Read more at https://errors.authjs.dev#signinerror                                                                             3:25:33 PM
[auth][cause]: TypeError: crypto.getRandomValues is not a function       

### Reproduction

-

### Describe the bug

node_modules/oauth4webapi/build/index.js:237:24

```
function randomBytes() {
    return b64u(crypto.getRandomValues(new Uint8Array(32)));
}
```

### Logs
Node.js v16.19.1.

_No response_

**Comment by Hebilicious** [comment] 2023-07-04 13:21
Could you please provide a reproduction with stackblitz / codesanbox or a repo please ? I don't have this issue.

**Comment by yk-sgr** [comment] 2023-07-08 21:42
Problem seems to be NodeJS 16.
Works for me with NodeJS 17 and upwards.

**Comment by Hebilicious** [comment] 2023-07-09 05:25
I'm gonna close this then, this package is designed specifically for non node environment, use node 18 + for development.

**Closed by Hebilicious** 2023-07-09 05:25 UTC
Labels: bug, needs reproduction
